//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RW_Frontend.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń fluent")]
        public string RemoveFluent {
            get {
                return ((string)(this["RemoveFluent"]));
            }
            set {
                this["RemoveFluent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń akcję")]
        public string RemoveAction {
            get {
                return ((string)(this["RemoveAction"]));
            }
            set {
                this["RemoveAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń agenta")]
        public string RemoveAgent {
            get {
                return ((string)(this["RemoveAgent"]));
            }
            set {
                this["RemoveAgent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń zdanie \"causes\"")]
        public string RemoveCauses {
            get {
                return ((string)(this["RemoveCauses"]));
            }
            set {
                this["RemoveCauses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń kwerendę \"after\"")]
        public string RemoveAfterQuery {
            get {
                return ((string)(this["RemoveAfterQuery"]));
            }
            set {
                this["RemoveAfterQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń kwerendę \"executable\"")]
        public string RemoveExecutableQuery {
            get {
                return ((string)(this["RemoveExecutableQuery"]));
            }
            set {
                this["RemoveExecutableQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń kwerendę \"engaged\"")]
        public string RemoveEngagedQuery {
            get {
                return ((string)(this["RemoveEngagedQuery"]));
            }
            set {
                this["RemoveEngagedQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nowy fluent")]
        public string AddFluent {
            get {
                return ((string)(this["AddFluent"]));
            }
            set {
                this["AddFluent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nową akcję")]
        public string AddAction {
            get {
                return ((string)(this["AddAction"]));
            }
            set {
                this["AddAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nowego agenta")]
        public string AddAgent {
            get {
                return ((string)(this["AddAgent"]));
            }
            set {
                this["AddAgent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nowe zdanie \"causes\"")]
        public string AddCauses {
            get {
                return ((string)(this["AddCauses"]));
            }
            set {
                this["AddCauses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nową kwerendę \"after\"")]
        public string AddAfterQuery {
            get {
                return ((string)(this["AddAfterQuery"]));
            }
            set {
                this["AddAfterQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nową kwerendę \"executable\"")]
        public string AddExecutableQuery {
            get {
                return ((string)(this["AddExecutableQuery"]));
            }
            set {
                this["AddExecutableQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nową kwerendę \"engaged\"")]
        public string AddEngagedQuery {
            get {
                return ((string)(this["AddEngagedQuery"]));
            }
            set {
                this["AddEngagedQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Znajdź wynik dla kwerendy \"after\"")]
        public string CalculateAfterQuery {
            get {
                return ((string)(this["CalculateAfterQuery"]));
            }
            set {
                this["CalculateAfterQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Znajdź wynik dla kwerendy \"executable\"")]
        public string CalculateExecutableQuery {
            get {
                return ((string)(this["CalculateExecutableQuery"]));
            }
            set {
                this["CalculateExecutableQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Znajdź wynik dla kwerendy \"engaged\"")]
        public string CalculateEngagedQuery {
            get {
                return ((string)(this["CalculateEngagedQuery"]));
            }
            set {
                this["CalculateEngagedQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń zdanie \"after\"")]
        public string RemoveAfter {
            get {
                return ((string)(this["RemoveAfter"]));
            }
            set {
                this["RemoveAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nowe zdanie \"after\"")]
        public string AddAfter {
            get {
                return ((string)(this["AddAfter"]));
            }
            set {
                this["AddAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj scenariusz")]
        public string AddScenario {
            get {
                return ((string)(this["AddScenario"]));
            }
            set {
                this["AddScenario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń scenariusz")]
        public string RemoveScenario {
            get {
                return ((string)(this["RemoveScenario"]));
            }
            set {
                this["RemoveScenario"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nowe zdanie \"initially\"")]
        public string AddInitially {
            get {
                return ((string)(this["AddInitially"]));
            }
            set {
                this["AddInitially"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń zdanie \"initially\"")]
        public string RemoveInitially {
            get {
                return ((string)(this["RemoveInitially"]));
            }
            set {
                this["RemoveInitially"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nowe zdanie \"observable\"")]
        public string AddObservable {
            get {
                return ((string)(this["AddObservable"]));
            }
            set {
                this["AddObservable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń zdanie \"observable\"")]
        public string RemoveObservable {
            get {
                return ((string)(this["RemoveObservable"]));
            }
            set {
                this["RemoveObservable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nowe zdanie \"always\"")]
        public string AddAlways {
            get {
                return ((string)(this["AddAlways"]));
            }
            set {
                this["AddAlways"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń zdanie \"always\"")]
        public string RemoveAlways {
            get {
                return ((string)(this["RemoveAlways"]));
            }
            set {
                this["RemoveAlways"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nowe zdanie \"impossible\"")]
        public string AddImpossible {
            get {
                return ((string)(this["AddImpossible"]));
            }
            set {
                this["AddImpossible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń zdanie \"impossible\"")]
        public string RemoveImpossible {
            get {
                return ((string)(this["RemoveImpossible"]));
            }
            set {
                this["RemoveImpossible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nowe zdanie \"releases\"")]
        public string AddReleases {
            get {
                return ((string)(this["AddReleases"]));
            }
            set {
                this["AddReleases"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń zdanie \"releases\"")]
        public string RemoveReleases {
            get {
                return ((string)(this["RemoveReleases"]));
            }
            set {
                this["RemoveReleases"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dodaj nowe zdanie \"noninertial\"")]
        public string AddNoninertial {
            get {
                return ((string)(this["AddNoninertial"]));
            }
            set {
                this["AddNoninertial"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usuń zdanie \"noninertial\"")]
        public string RemoveNoninertial {
            get {
                return ((string)(this["RemoveNoninertial"]));
            }
            set {
                this["RemoveNoninertial"] = value;
            }
        }
    }
}
